### ISSUE TITLE
Unable to get vertices due to invalid query

### ISSUE THREAD

**Issue by zjffdu** [JanusGraph/janusgraph-visualizer#1]
Here's the error I get:
```
Invalid query. Please execute a query to get a set of vertices
```
I think g.V() should be valid.

![image](https://github.com/user-attachments/assets/40cabdf0-b46a-49ce-b8e5-b0858d67d401)

**Comment by porunov** [comment]
Yeah, we need to improve the error log. Right now you may receive it because JanusGraph visualizer was not being able to connect to the Gremlin Server. 

I would recommend to use Quick Start Guide which starts both docker containers on the same host machine with the default ports. In that case it will work as expected: https://github.com/JanusGraph/janusgraph-visualizer?tab=readme-ov-file#quick-start-guide


Still I propose to leave this issue open to improve error message as the error message doesn’t specify connection issues right now.

**Comment by zjffdu** [comment]
@porunov Here's the only log I find in docker container
```
2024-11-06 19:51:20 Simple gremlin-proxy server listening on port 3001!
2024-11-06 19:51:33 AggregateError [ECONNREFUSED]: 
2024-11-06 19:51:33     at internalConnectMultiple (node:net:1118:18)
2024-11-06 19:51:33     at afterConnectMultiple (node:net:1685:7)
```

And this is the command I use to start docker container, not sure what's missing
```
docker run --rm -d -p 3000:3000 -p 3001:3001 --name=janusgraph-visualizer --network=mynet janusgraph/janusgraph-visualizer:latest
```

**Comment by porunov** [comment]
> @porunov Here's the only log I find in docker container
> 
> ```
> 2024-11-06 19:51:20 Simple gremlin-proxy server listening on port 3001!
> 2024-11-06 19:51:33 AggregateError [ECONNREFUSED]: 
> 2024-11-06 19:51:33     at internalConnectMultiple (node:net:1118:18)
> 2024-11-06 19:51:33     at afterConnectMultiple (node:net:1685:7)
> ```
> 
> And this is the command I use to start docker container, not sure what's missing
> 
> ```
> docker run --rm -d -p 3000:3000 -p 3001:3001 --name=janusgraph-visualizer --network=mynet janusgraph/janusgraph-visualizer:latest
> ```

‘ECONNREFUSED’ - means it cannot connect to your Gremlin Server. What host and port are you running your server? 
Sometimes SELinux may also prevent you from accessing ports which are not explicitly allowed.

**Comment by zjffdu** [comment]
I am using Mac. Here's the command I use to run janusgraph.
```
docker run -it -p 8182:8182 --name janusgraph --network mynet janusgraph/janusgraph:latest
```

And I can connect to this janusgraph via puppygraph.

```
docker run -d --rm -p 8081:8081 --name puppygraph  -e PUPPYGRAPH_USERNAME=puppygraph -e PUPPYGRAPH_PASSWORD=puppygraph  -e PORT=8081 -e  USE_GREMLIN_AUTH=false  -e GREMLINSERVER_HOST=janusgraph:8182 --network mynet puppygraph/puppygraph-query:latest
```

**Comment by porunov** [comment]
> I am using Mac. Here's the command I use to run janusgraph.
> 
> ```
> docker run -it -p 8182:8182 --name janusgraph --network mynet janusgraph/janusgraph:latest
> ```
> 
> And I can connect to this janusgraph via puppygraph.
> 
> ```
> docker run -d --rm -p 8081:8081 --name puppygraph  -e PUPPYGRAPH_USERNAME=puppygraph -e PUPPYGRAPH_PASSWORD=puppygraph  -e PORT=8081 -e  USE_GREMLIN_AUTH=false  -e GREMLINSERVER_HOST=janusgraph:8182 --network mynet puppygraph/puppygraph-query:latest
> ```

So it seems you are using `janusgraph` hostname for you JanusGraph Server, but when `janusgraph-visualizer` starts it doesn't know what hostname or IP address to use to connect to the running instance. Thus, it tries to connect to `localhost` by default and there is no JanusGraph instance running on `localhost`.
In this case you need to let `janusgraph-visualizer` know the hostname to use by setting `GREMLIN_HOST` environment variable.

You can start your JanusGraph-Visualizer like this in your case:
```
docker run --rm -d -p 3000:3000 -p 3001:3001 -e GREMLIN_HOST=janusgraph --name=janusgraph-visualizer --network=mynet janusgraph/janusgraph-visualizer:latest
```

**Comment by zjffdu** [comment]
Thanks, it works
