### ISSUE TITLE
How to use specific property value for node display value.

### ISSUE THREAD

**Issue by zjffdu** [JanusGraph/janusgraph-visualizer#3]
Here's the node I insert into janusgraph. But it use the `updatedBy` as the display value. How can I specific the property value as the display value.

![image](https://github.com/user-attachments/assets/7cba96dd-8437-4dc0-935a-ddbb8515d527)

**Comment by porunov** [comment]
Click on the property, open settings, and specify your vertex label in `Node Type` and your vertex property in `Label Field`.
- Node Type is responsible to use the same color for a set of vertices which have the same label.
- Label Field is the text which is used under each vertex.

![NodeLabels](https://github.com/user-attachments/assets/72fd2aee-e6fe-44f1-8cdc-16b1b2ccc7f3)

**Comment by zjffdu** [comment]
Thanks @porunov , it works now. One minor suggestion, I think the double quote around label could be removed.
![image](https://github.com/user-attachments/assets/f9666c92-19a5-47b9-a263-c83806f0b738)
